apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
  name: ftps
  labels:
    app: ftps
spec:
  type: LoadBalancer
  selector:
    app: ftps
  ports:
  
  - name: ftps
    port: 21
    targetPort: 21

  - name: data
    port: 20
    targetPort: 20

  - name: min
    port: 21009
    targetPort: 21009
  - name: mid
    port: 21010
    targetPort: 21010
  - name: max
    port: 21011
    targetPort: 21011

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
  labels:
    app: ftps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: ftps_service
        imagePullPolicy: Never
        ports:
        - name: ftps
          containerPort: 21
        - name: data
          containerPort: 20
        - name: min
          containerPort: 21009
        - name: mid
          containerPort: 21010
        - name: max
          containerPort: 21011